Fixes #1994 - clean up mountnfs.sh and firstrun in files.d

diff --git a/src/UbuntuDiskless/files.d/firstrun b/src/UbuntuDiskless/files.d/firstrun
--- a/src/UbuntuDiskless/files.d/firstrun
+++ b/src/UbuntuDiskless/files.d/firstrun
@@ -7,116 +7,131 @@ set -e
 
 ## firstrun for diskless mds
 File="/etc/init.d/firstrun"
-Link="/etc/rc2.d/S00firstrun"
-
-INSSERV="/sbin/insserv"
-if ! [[ -x "${Parm_RootLocation}$INSSERV" ]]; then
-        INSSERV="/usr/lib/insserv/insserv"
-fi
-if ! [[ -x "${Parm_RootLocation}$INSSERV" ]]; then
-        echo "No insserv found.  Exiting."
-        exit 1
-fi
 
 #echo "${Content}" > "${Parm_RootLocation}/${File}"
-cat >"${Parm_RootLocation}/${File}" <<'EOF'
-#!/bin/bash
-### BEGIN INIT INFO
-# Provides:          firstrun
-# Required-Start:    $remote_fs
-# Required-Stop:     $remote_fs
-# Should-Start:
-# Default-Start:     S 2
-# Default-Stop:
-# Short-Description: firstrun
-# Description:       This script is run the first time linuxmce boots
-### END INIT INFO #
+cat <<-'EOF' >"${Parm_RootLocation}/${File}"
+	#!/bin/bash
+	### BEGIN INIT INFO
+	# Provides:          firstrun
+	# Required-Start:    $remote_fs
+	# Required-Stop:     $remote_fs
+	# Should-Start:
+	# Default-Start:     2 3 4 5
+	# Default-Stop:
+	# Short-Description: firstrun
+	# Description:       This script is run the first time linuxmce boots
+	### END INIT INFO #
 
-if ! [[ -d "${Parm_RootLocation}/$(dirname $File)" ]]; then
-	mkdir -p "${Parm_RootLocation}/$(dirname $File)"
-fi
+	if ! [[ -d "${Parm_RootLocation}/$(dirname $File)" ]]; then
+		mkdir -p "${Parm_RootLocation}/$(dirname $File)"
+	fi
 
-do_start () {
-trap '${INSSERV} -rfv firstrun' EXIT
+	raspbian() {
+		trap '${INSSERV} -rfv firstrun' EXIT
 
-DEVICEDATA_DISTRO_Raspbian_Wheezy_CONST=19
+		INSSERV=$(which insserv)
 
-. /usr/pluto/bin/Config_Ops.sh
+		echo -e "\n\n\n\n\n\n\n\n\nRPI FIRSTRUN\n\n\n\n\n\n\n\n\n" >&2
 
-if [[ "$DEVICEDATA_DISTRO_Raspbian_Wheezy_CONST" -eq "$PK_Distro" ]]; then
+		# copy contents of /boot to /sdcard
+		cp /boot/* /sdcard/
 
-	INSSERV="/sbin/insserv"
+		# not required with working u-boot
+		# remove u-boot kernel from /sdcard/config.txt
+		#[[ ! -f /sdcard/config.txt.lmcebackup ]] && cp /sdcard/config.txt /sdcard/config.txt.lmcebackup
+		#sed -i 's/^[kK]ernel/#&/' /sdcard/config.txt
+		# add extra kernel boot args to /sdcard/cmdline.txt
+		#[[ ! -f /sdcard/cmdline.txt.lmcebackup ]] && cp /sdcard/cmdline.txt /sdcard/cmdline.txt.lmcebackup
+		#echo "dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline rootwait root=/dev/nfs nfsroot=192.168.80.1:/usr/pluto/diskless/$PK_Device ip=dhcp rootfstype=nfs" > /sdcard/cmdline.txt
 
-	echo -e "\n\n\n\n\n\n\n\n\nRPI FIRSTRUN\n\n\n\n\n\n\n\n\n"
+		"$INSSERV" -fv linuxmce
+		"$INSSERV" -rfv firstrun
+		reboot
+		return 1
+	}
 
-	# copy contents of /boot to /sdcard
-	cp /boot/* /sdcard/
+	ubuntu() {
+		trap 'update-rc.d -f firstrun remove' EXIT
 
-	# not required with working u-boot
-	# remove u-boot kernel from /sdcard/config.txt
-	#[[ ! -f /sdcard/config.txt.lmcebackup ]] && cp /sdcard/config.txt /sdcard/config.txt.lmcebackup
-	#sed -i 's/^[kK]ernel/#&/' /sdcard/config.txt
-	# add extra kernel boot args to /sdcard/cmdline.txt
-	#[[ ! -f /sdcard/cmdline.txt.lmcebackup ]] && cp /sdcard/cmdline.txt /sdcard/cmdline.txt.lmcebackup
-	#echo "dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline rootwait root=/dev/nfs nfsroot=192.168.80.1:/usr/pluto/diskless/$PK_Device ip=dhcp rootfstype=nfs" > /sdcard/cmdline.txt
+		apt-get update
+		update-pciids
 
-	"${INSSERV}" -fv linuxmce
-	"${INSSERV}" -rfv firstrun
-	reboot
-	exit 0
-fi
+		## Handle libdvdcss2
+		dpkg -l libdvdcss2 | grep ^ii || find /usr/pluto/deb-cache/ -iname 'libdvdcss*' -exec dpkg -i {} \;
 
-#"${INSSERV}" -fv linuxmce
-#"${INSSERV}" -rfv firstrun
-exit 0
+		## Install video driver
+		. /usr/pluto/bin/Utils.sh
+		CheckVideoDriver
+		update-rc.d -f firstrun remove
 
-apt-get update
-update-pciids
+		if echo "$Best_Video_Driver" | grep -Eq '(nvidia|fglrx|via|virge|savage)'; then
+			sleep 5
+			reboot
+		fi
+		return 0
+	}
 
-## Handle libdvdcss2
-dpkg -l libdvdcss2 | grep ^ii || find /usr/pluto/deb-cache/ -iname 'libdvdcss*' -exec dpkg -i {} \;
+	start() {
+		DEVICEDATA_DISTRO_Raspbian_Wheezy_CONST=19
 
-## Install video driver
-. /usr/pluto/bin/Utils.sh
-CheckVideoDriver
-sleep 5
-if echo "$Best_Video_Driver" | grep -Eq '(nvidia|fglrx|via|virge|savage)'; then
-	rm -f "$Link"
-	reboot
-fi
-}
+		. /usr/pluto/bin/Config_Ops.sh
 
-do_status () {
-        return 0
-}
+		case "$PK_Distro" in
+			"$DEVICEDATA_DISTRO_Raspbian_Wheezy_CONST")
+				raspbian
+				err=$?
+				;;
+			*)
+				ubuntu
+				err=$?
+		esac
+		return $err
+	}
 
-case "$1" in
-  start|"")
-        do_start
-        ;;
-  restart|reload|force-reload)
-        echo "Error: argument '$1' not supported" >&2
-        exit 3
-        ;;
-  stop)
-        # No-op
-        ;;
-  status)
-        do_status
-        exit $?
-        ;;
-  *)
-        echo "Usage: firstrun [start|stop|status]" >&2
-        exit 3
-        ;;
+	status() {
+	        status_of_proc firstrun firstrun
+		return $?
+	}
+
+	case "$1" in
+	  start|"")
+	        $1
+		retval=$?
+	        ;;
+	  restart|reload|force-reload)
+	        echo "Error: argument '$1' not supported" >&2
+		retval=3
+	        ;;
+	  stop)
+	        : # No-op
+		retval=$?
+	        ;;
+	  status)
+	        $1
+	        retval=$?
+	        ;;
+	  *)
+	        echo "Usage: $0 [start|stop|status]" >&2
+		retval=3
+	esac
+	exit $retval
+	:
+	EOF
+
+DISTRO=$(LC_ALL=C chroot ${Parm_RootLocation} lsb_release -is)
+case "$DISTRO" in
+        Debian)
+                # debian/raspbian (LSB)
+                INSSERV=$(LC_ALL=C chroot ${Parm_RootLocation} which insserv)
+                LC_ALL=C chroot "${Parm_RootLocation}" "${INSSERV}" -fv firstrun >/dev/null
+                ;;
+        Ubuntu)
+                # ubuntu (sysv)
+                LC_ALL=C chroot "${Parm_RootLocation}" update-rc.d -f firstrun start 50 2 3 4 5 . >/dev/null
+                ;;
+        *)
+		echo "Unknown Moon Distro!" >&2
+		exit 1
+                ;;
 esac
-
-:
-EOF
-
 chmod +x "${Parm_RootLocation}/${File}"
-LC_ALL=C chroot "${Parm_RootLocation}" "${INSSERV}" -fv firstrun
-
-#pushd "${Parm_RootLocation}$(dirname $Link)" >/dev/null
-#ln -sf "../init.d/$(basename $File)" "$(basename $Link)"
-#popd >/dev/null
