Refs #315 - Load Zaptel modules to enable speak in the house and meetme based functionality

diff --git a/src/BootScripts/linuxmce b/src/BootScripts/linuxmce
--- a/src/BootScripts/linuxmce
+++ b/src/BootScripts/linuxmce
@@ -156,6 +156,9 @@ if [ "$AutostartCore" -eq "1" ] ; then
 	StartDaemon  "Starting Dhcp Plugin" "/usr/pluto/bin/Dhcpd-Plugin.sh" "DhcpdPlugin"
 	StartDaemon  "Start PNP MD Plugin" "/usr/pluto/bin/Start_NewMD_interactor.sh" "NewMDinteractor"
 	StartDaemon  "Start Voicemail Monitor" "/usr/pluto/bin/VoiceMailMonitor.sh" "VoiceMailMonitor"
+	
+	# Verify zaptel-modules is installed, and install it otherwise.
+	dpkg -l zaptel-modules-`uname -r` || apt-get install zaptel-modules-`uname -r` || echo "***ERROR*** INSTALLING ZAPTEL MODULE - TELECOM TRANSFER/MEETME/CONFERENCING NOT WORKING****">>/var/lib/pluto/DCERouter.log
 fi
 StartService "Loading Kernel Modules" "/usr/pluto/bin/LoadModules.sh"
 StartService "Reporting Machine Status" "/usr/pluto/bin/Report_Machine_Status.sh" "&"
