updated debian directory with files from debian-multimedia.org

diff --git a/external/mythtv/mythtv/debian/mythtv-database.postinst b/external/mythtv/mythtv/debian/mythtv-database.postinst
--- a/external/mythtv/mythtv/debian/mythtv-database.postinst
+++ b/external/mythtv/mythtv/debian/mythtv-database.postinst
@@ -1,15 +1,4 @@
-#!/bin/sh
-
-set -e
-
-# summary of how this script can be called:
-#        * <postinst> `configure' <most-recently-configured-version>
-#        * <old-postinst> `abort-upgrade' <new version>
-#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
-#          <new-version>
-#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
-#          <failed-install-package> <version> `removing'
-#          <conflicting-package> <version>
+#!/bin/sh -e
 
 escape_quotes() {
     cat <<EOF | sed -e "s/'/\\\\'/g"
@@ -24,7 +13,7 @@ DoSQL() {
     local database="$4"
     local statement="`escape_quotes \"$5\"`"
     local tmp=`tempfile -m 600`
-        cat <<EOF >$tmp
+	cat <<EOF >$tmp
 $admin_password
 EOF
     perl -e "
@@ -32,8 +21,8 @@ use DBI;
 chomp(\$password=<>);
 @statements=split(/;/, '$statement');
 \$db = DBI->connect('dbi:mysql:host=$host;database=$database',
-                    '$admin_username', \$password,
-                    { PrintError => 0 }) || die 'Failed to connect to database: ' . \$DBI::errstr;
+		    '$admin_username', \$password,
+		    { PrintError => 0 }) || die 'Failed to connect to database: ' . \$DBI::errstr;
 for \$s (@statements) { \$db->do(\$s) || die 'Failed to execute SQL: ' . \$s . '\n' . \$DBI::errstr; }
 " < $tmp
     ret=$?
@@ -45,78 +34,86 @@ MYTHSQL=/usr/share/mythtv/mythsql
 
 case "$1" in
     configure)
-        . /usr/share/debconf/confmodule
+	. /usr/share/debconf/confmodule
 
-        db_get mythtv/mysql_admin_user
-        admin_username="$RET"
-        db_get mythtv/mysql_admin_password
-        admin_password="$RET"
+	db_get mythtv/mysql_admin_user
+	admin_username="$RET"
+	db_get mythtv/mysql_admin_password
+	admin_password="$RET"
 
-        db_get mythtv/mysql_host
-        hostname="$RET"
-        db_get mythtv/mysql_mythtv_dbname
-        database="$RET"
+	db_get mythtv/mysql_host
+	hostname="$RET"	
 
-        if ! DoSQL "$hostname" "$admin_username" "$admin_password" "$database" "SELECT NULL" 2>/dev/null; then
+	if test -z "$hostname"; then
+	    hostname=localhost
+	fi
 
-            if ! DoSQL "$hostname" "$admin_username" "$admin_password" "" \
-              "CREATE DATABASE $database"; then
-              echo "Failed to create database (incorrect admin username/password?)" >&2
-              echo "If you supplied incorrect information, try:" >&2
-              echo "dpkg-reconfigure --force mythtv-database" >&2
-              exit 1
-            fi
+	db_get mythtv/mysql_mythtv_dbname
+	database="$RET"
 
-        fi
+	if ! DoSQL "$hostname" "$admin_username" "$admin_password" "$database" "SELECT NULL" 2>/dev/null; then
 
-        db_get mythtv/mysql_mythtv_user
-        mythtv_username="$RET"
-        db_get mythtv/mysql_mythtv_password
-        mythtv_password="$RET"
+	    if ! DoSQL "$hostname" "$admin_username" "$admin_password" "" \
+	      "CREATE DATABASE $database"; then
+	      echo "Failed to create database (incorrect admin username/password?)" >&2
+	      echo "It's also possible that mysql-server wasn't running.  After install" >&2
+	      echo "is completed, you will need to make sure mysql-server is running" >&2
+	      echo "and that you supplied correct information. Try:" >&2
+	      echo "sudo dpkg-reconfigure mythtv-database" >&2
+	      # silently exit, instead pop up a notification for user indicating this
+	      exit 0
+	      unud=/var/lib/update-notifier/user.d
+	      if test -d $uund; then
+	      cp -f /usr/share/mythtv/mythtv-reconfigure-required.update-notifier \
+	              /var/lib/update-notifier/user.d/mythtv-reconfigure-required
+	      fi
+	    fi
 
-        DoSQL "$hostname" "$admin_username" "$admin_password" "$database" \
-            "GRANT ALL PRIVILEGES ON $database.* TO $mythtv_username@localhost IDENTIFIED BY '$mythtv_password'"
+	fi
 
-        DoSQL "$hostname" "$admin_username" "$admin_password" "$database" \
-            "GRANT ALL PRIVILEGES ON $database.* TO
-                $mythtv_username@'%' IDENTIFIED BY '$mythtv_password'"
+	db_get mythtv/mysql_mythtv_user
+	mythtv_username="$RET"
+	db_get mythtv/mysql_mythtv_password
+	mythtv_password="$RET"
 
-        # Upgrades from old versions where the database was not
-        # automatically upgraded (pre-0.12)
+	DoSQL "$hostname" "$admin_username" "$admin_password" "$database" \
+	    "GRANT ALL PRIVILEGES ON $database.* TO $mythtv_username@localhost IDENTIFIED BY '$mythtv_password'"
 
-        if test -n "$2" && dpkg --compare-versions "$2" lt 0.8-1; then
-            $MYTHSQL < /usr/share/mythtv/sql/0-7-to-0-8.sql
-        fi
-        
-        if test -n "$2" && dpkg --compare-versions "$2" lt 0.9-1; then
-            $MYTHSQL < /usr/share/mythtv/sql/0-8-to-0-9.sql
-        fi
-        
-        if test -n "$2" && dpkg --compare-versions "$2" lt 0.10-1; then
-            $MYTHSQL < /usr/share/mythtv/0.9-to-0.10.sql
-        fi
-        
-        if test -n "$2" && dpkg --compare-versions "$2" lt 0.11-1; then
-            $MYTHSQL < /usr/share/mythtv/sql/0.10-to-0.11.sql
-        fi
+	DoSQL "$hostname" "$admin_username" "$admin_password" "$database" \
+	    "GRANT ALL PRIVILEGES ON $database.* TO
+		$mythtv_username@'%' IDENTIFIED BY '$mythtv_password'"
 
-        ;;
+	# Upgrades from old versions where the database was not
+	# automatically upgraded (pre-0.12)
+
+	if test -n "$2" && dpkg --compare-versions "$2" lt 0.8-1; then
+	    $MYTHSQL < /usr/share/mythtv/sql/0-7-to-0-8.sql
+	fi
+	
+	if test -n "$2" && dpkg --compare-versions "$2" lt 0.9-1; then
+	    $MYTHSQL < /usr/share/mythtv/sql/0-8-to-0-9.sql
+	fi
+	
+	if test -n "$2" && dpkg --compare-versions "$2" lt 0.10-1; then
+	    $MYTHSQL < /usr/share/mythtv/0.9-to-0.10.sql
+	fi
+	
+	if test -n "$2" && dpkg --compare-versions "$2" lt 0.11-1; then
+	    $MYTHSQL < /usr/share/mythtv/sql/0.10-to-0.11.sql
+	fi
+
+	;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
 
-        ;;
+	;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
-        exit 1
-        ;;
+	echo "postinst called with unknown argument \`$1'" >&2
+	exit 1
+	;;
 esac
-
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
 
 #DEBHELPER#
 
 exit 0
-
-
